[[redirects]]
  from = "/api/*"
  to = "https://exam.razoyo.com/api/cars"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://exam.razoyo.com/api/cars/:id"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200